//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.12 at 10:20:10 AM CEST 
//

package de.ismll.runtime.files;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.xmedia.ismll.sparqlrepository package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Queries_QNAME = new QName(
			"http://ismll.uni-hildesheim.de/xmedia/sparql", "queries");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: org.xmedia.ismll.sparqlrepository
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Queries }
	 * 
	 */
	public Queries createQueries() {
		return new Queries();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Queries }{@code
	 * >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://ismll.uni-hildesheim.de/xmedia/sparql", name = "queries")
	public JAXBElement<Queries> createQueries(Queries value) {
		return new JAXBElement<Queries>(_Queries_QNAME, Queries.class, null,
				value);
	}

	/**
	 * Create an instance of {@link Query }
	 * 
	 */
	public Query createQuery() {
		return new Query();
	}

}
