//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.12 at 10:20:10 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ismll.uni-hildesheim.de/xmedia/sparql", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.ismll.runtime.files;

